### ISSUE TITLE
Add more quotes and researcher commentary

### ISSUE THREAD

**Issue by plastichotsprings** [ozzmotic/care-brokers#2]
Need to come up with a way to show researcher commentary that is distinct from participant quotes

**Comment by ozzmotic** [comment]
Info about who the participant was, a pseudonym for example, what sector they worked in

**Comment by ozzmotic** [comment]
Try to visually separate the quotes somehow, possibly through a centered asterisk

**Comment by ozzmotic** [comment]
OR 

a three column layout with each broker as a column -- as a way to compare quotes from different broker situations?
